
/* ------------------------------- shell ------------------------------ */
var LOGO=[
'<svg class="mark" viewBox="0 0 200 200" role="img" aria-label="Shan Village"><defs>',
'  <linearGradient id="gold" x1="0" y1="0" x2="0" y2="1">',
'    <stop offset="0" stop-color="#F7E39A"/><stop offset=".28" stop-color="#E3BE63"/>',
'    <stop offset=".55" stop-color="#B8860F"/><stop offset=".78" stop-color="#E9C86E"/>',
'    <stop offset="1" stop-color="#8A5F12"/>',
'  </linearGradient>',
'  <linearGradient id="goldFlat" x1="0" y1="0" x2="0" y2="1">',
'    <stop offset="0" stop-color="#E8C777"/><stop offset=".5" stop-color="#C79A38"/>',
'    <stop offset="1" stop-color="#A97C1E"/>',
'  </linearGradient>',
'  <path id="arc" d="M30 104 A70 70 0 0 1 170 104"/>',
'  <clipPath id="hutClip"><path d="M100 33 L173 99 L154 99 L154 134 L46 134 L46 99 L27 99 Z"/></clipPath>',
'  <clipPath id="discClip"><circle cx="100" cy="100" r="92"/></clipPath>',
'</defs>',
'<circle cx="100" cy="100" r="99" fill="#F0873A"/>',
'<circle cx="100" cy="100" r="92" fill="#000"/>',
'<!-- hut: black ground with alternating orange / red bands -->',
'<g clip-path="url(#hutClip)">',
'  <rect x="20" y="28" width="160" height="112" fill="#000"/>',
'  <g>',
'    <rect x="20" y="38"  width="160" height="8" fill="#F0873A"/>',
'    <rect x="20" y="49"  width="160" height="8" fill="#E63329"/>',
'    <rect x="20" y="60"  width="160" height="8" fill="#F0873A"/>',
'    <rect x="20" y="71"  width="160" height="8" fill="#E63329"/>',
'    <rect x="20" y="82"  width="160" height="8" fill="#F0873A"/>',
'    <rect x="20" y="93"  width="160" height="8" fill="#E63329"/>',
'    <rect x="20" y="104" width="160" height="8" fill="#F0873A"/>',
'    <rect x="20" y="115" width="160" height="8" fill="#E63329"/>',
'    <rect x="20" y="126" width="160" height="8" fill="#F0873A"/>',
'  </g>',
'</g>',
'<path d="M100 33 L173 99 L154 99 L154 134 L46 134 L46 99 L27 99 Z"',
'      fill="none" stroke="#E63329" stroke-width="3.4" stroke-linejoin="round"/>',
'<!-- stepped gold base -->',
'<g clip-path="url(#discClip)">',
'  <rect x="8" y="148" width="184" height="9" fill="url(#goldFlat)"/>',
'  <rect x="8" y="161" width="184" height="9" fill="url(#goldFlat)"/>',
'  <rect x="8" y="174" width="184" height="9" fill="url(#goldFlat)"/>',
'  <rect x="8" y="187" width="184" height="9" fill="url(#goldFlat)"/>',
'</g>',
'<!-- arched wordmark -->',
'<text font-family="Georgia,\'Times New Roman\',serif" font-size="27" font-weight="700"',
'      fill="url(#gold)" stroke="#4A3208" stroke-width=".5" letter-spacing="2.4">',
'  <textPath href="#arc" startOffset="50%" text-anchor="middle">SHAN VILLAGE</textPath>',
'</text>',
'<!-- SV monogram -->',
'<text x="100" y="120" font-family="Georgia,\'Times New Roman\',serif" font-size="78"',
'      font-style="italic" font-weight="700" text-anchor="middle"',
'      fill="url(#gold)" stroke="#FFF7E4" stroke-width="2.6" paint-order="stroke">SV</text></svg>'
].join('');

var SHELL=[
'<header class="app-header">',
LOGO,
'  <div><h1>Inventory</h1><div class="sub">Shan Village</div></div>',
'  <div class="right">',
'    <select class="locpick" id="locPick" aria-label="Location"></select>',
'    <button class="btn-lock" id="lockBtn"></button>',
'    <div class="stamp" id="stamp"></div>',
'  </div>',
'</header>',
'<nav class="tabs" role="tablist" aria-label="Sections">',
'  <button role="tab" id="tab-count" aria-selected="true" hidden>Stock take</button>',
'  <button role="tab" id="tab-stock" aria-selected="false">Current stock</button>',
'  <button role="tab" id="tab-items" aria-selected="false" hidden>Item master</button>',
'  <button role="tab" id="tab-settings" aria-selected="false" hidden>Settings</button>',
'  <button role="tab" id="tab-audit" aria-selected="false" hidden>Audit log</button>',
'  <button role="tab" id="tab-dash" aria-selected="false">Dashboard</button>',
'</nav>',
'<main>',
'  <div id="banner"></div>',

/* ---- current stock ---- */
'  <section class="panel" id="panel-stock" hidden>',
'    <div class="card card-pad">',
'      <div class="grid3">',
'        <div class="field"><label class="lbl" for="stSearch">Search</label>',
'          <input class="f" id="stSearch" placeholder="Name or SKU" autocomplete="off"></div>',
'        <div class="field"><label class="lbl" for="stCat">Category</label><select class="f" id="stCat"></select></div>',
'        <div class="field"><label class="lbl" for="stStatus">Stock status</label><select class="f" id="stStatus">',
'          <option value="">All</option><option value="out">Out of stock</option><option value="crit">Critical</option>',
'          <option value="low">Low stock</option><option value="ok">Healthy</option><option value="over">Overstock</option>',
'        </select></div>',
'      </div>',
'      <div class="row no-print" style="margin-top:11px"><span class="faint" id="stCount"></span>',
'        <div class="spacer"></div><button class="btn" id="stPrint">Print</button></div>',
'    </div>',
'    <div class="wrap"><table id="stockTable"></table></div>',
'  </section>',

/* ---- stock take ---- */
'  <section class="panel" id="panel-count" hidden>',
'    <div id="countHome">',
'      <div class="card card-pad">',
'        <h2 class="sec">Start a stock take</h2>',
'        <p class="sec">One count per location per day. Counting is judged against stock as it stands when you start.</p>',
'        <div class="grid2" style="margin-top:11px">',
'          <div class="field"><label class="lbl" for="ctLoc">Location</label><select class="f" id="ctLoc"></select></div>',
'          <div class="field"><label class="lbl" for="ctDate">Date</label><input class="f" id="ctDate" type="date"></div>',
'        </div>',
'        <div class="field" style="margin-top:11px"><label class="lbl">How do you want to count?</label>',
'          <div class="chips" id="ctMode">',
'            <button type="button" class="chip" data-mode="manual" aria-pressed="true">One by one, with a photo</button>',
'            <button type="button" class="chip" data-mode="list" aria-pressed="false">Work down the item list</button>',
'          </div>',
'          <div class="hint" id="ctModeHint"></div></div>',
'        <div class="field" id="ctCatWrap" hidden><label class="lbl" for="ctCat">Only this category</label>',
'          <select class="f" id="ctCat"></select></div>',
'        <div id="ctWarn" style="margin-top:11px"></div>',
'        <button class="btn-big" id="ctStart" style="margin-top:13px">Start counting</button>',
'      </div>',
'      <div class="card card-pad"><h2 class="sec">Stock takes</h2>',
'        <div class="wrap" style="margin-top:9px;border:0"><table id="takesTable"></table></div></div>',
'    </div>',
'    <div id="countRun" hidden>',
'      <div class="progwrap">',
'        <div class="row" style="margin-bottom:7px"><strong id="runTitle"></strong>',
'          <div class="spacer"></div><button class="btn no-print" id="runClose">Close</button></div>',
'        <div class="progbar"><i id="runBar" style="width:0%"></i></div>',
'        <div class="progtext" id="runText"></div>',
'      </div>',
'      <button class="btn-big no-print" id="runAdd" style="margin:10px 0">Add an item to this count</button>',
'      <div class="card card-pad no-print"><div class="grid2">',
'        <div class="field"><label class="lbl" for="runSearch">Find an item</label>',
'          <input class="f" id="runSearch" placeholder="Name or SKU" autocomplete="off"></div>',
'        <div class="field"><label class="lbl" for="runShow">Show</label><select class="f" id="runShow">',
'          <option value="all">All items</option><option value="todo">Not counted yet</option>',
'          <option value="done">Counted</option><option value="var">With a variance</option></select></div>',
'      </div></div>',
'      <div id="runList" style="display:flex;flex-direction:column;gap:9px"></div>',
'      <div class="card card-pad no-print" id="runFoot"></div>',
'    </div>',
'  </section>',

/* ---- items ---- */
'  <section class="panel" id="panel-items" hidden>',
'    <div class="card card-pad">',
'      <div class="row"><h2 class="sec">Item master</h2><div class="spacer"></div>',
'        <button class="btn" id="imImport">Import CSV</button>',
'        <button class="btn" id="imExport">Export</button>',
'        <button class="btn primary" id="imAdd">Add item</button></div>',
'      <div class="grid3" style="margin-top:11px">',
'        <div class="field"><label class="lbl" for="imSearch">Search</label>',
'          <input class="f" id="imSearch" placeholder="Name or SKU" autocomplete="off"></div>',
'        <div class="field"><label class="lbl" for="imCat">Category</label><select class="f" id="imCat"></select></div>',
'        <div class="field"><label class="lbl" for="imActive">Show</label><select class="f" id="imActive">',
'          <option value="1">Active only</option><option value="0">Including inactive</option></select></div>',
'      </div>',
'    </div>',
'    <div class="wrap"><table id="itemsTable"></table></div>',
'  </section>',

/* ---- settings ---- */
'  <section class="panel" id="panel-settings" hidden>',
'    <div class="card card-pad"><h2 class="sec">Locations</h2>',
'      <p class="sec">Stock is held separately at each. Counting never mixes them.</p>',
'      <div class="wrap" style="margin-top:9px;border:0"><table id="locsTable"></table></div>',
'      <div class="row no-print" style="margin-top:9px"><input class="f" id="newLoc" placeholder="New location name" style="max-width:260px">',
'        <button class="btn" id="addLoc">Add</button></div></div>',
'    <div class="card card-pad"><h2 class="sec">Categories</h2>',
'      <div class="wrap" style="margin-top:9px;border:0"><table id="catsTable"></table></div>',
'      <div class="row no-print" style="margin-top:9px"><input class="f" id="newCat" placeholder="New category" style="max-width:260px">',
'        <button class="btn" id="addCat">Add</button></div></div>',
'    <div class="card card-pad"><h2 class="sec">Variance tolerance</h2>',
'      <p class="sec">Shan Village policy, not a fixed rule. Set these before you rely on the variance report.</p>',
'      <div class="grid3" style="margin-top:11px">',
'        <div class="field"><label class="lbl" for="sTolPct">Minor variance up to (%)</label><input class="f num" id="sTolPct" type="number" min="0" step="0.5"></div>',
'        <div class="field"><label class="lbl" for="sTolQty">or up to (units)</label><input class="f num" id="sTolQty" type="number" min="0" step="0.1"></div>',
'        <div class="field"><label class="lbl" for="sRevPct">Review required above (%)</label><input class="f num" id="sRevPct" type="number" min="0" step="1"></div>',
'        <div class="field"><label class="lbl" for="sRevVal">Review required above value</label><input class="f num" id="sRevVal" type="number" min="0" step="1"></div>',
'        <div class="field"><label class="lbl" for="sCur">Currency</label><input class="f" id="sCur" maxlength="6"></div>',
'        <div class="field"><label class="lbl" for="sKeep">Keep photos for (days)</label><input class="f num" id="sKeep" type="number" min="1" step="1"></div>',
'      </div></div>',
'    <div class="card card-pad"><h2 class="sec">Photo rules</h2>',
'      <div class="grid2" style="margin-top:9px">',
'        <div class="field"><label class="lbl" for="sPhoto">Photo on a counted item</label><select class="f" id="sPhoto">',
'          <option value="off">Optional</option><option value="var">Required when there is a variance</option>',
'          <option value="all">Required on every item</option></select></div>',
'        <div class="field"><label class="lbl" for="sComment">Comment on a large variance</label><select class="f" id="sComment">',
'          <option value="off">Optional</option><option value="on">Required above the review threshold</option></select></div>',
'      </div></div>',
'    <div class="row no-print"><button class="btn primary" id="setSave">Save settings</button></div>',
'  </section>',

/* ---- audit ---- */
'  <section class="panel" id="panel-audit" hidden>',
'    <div class="card card-pad"><h2 class="sec">Audit log</h2>',
'      <p class="sec">Every change that matters, newest first, in '+'Abu Dhabi time.</p></div>',
'    <div class="wrap"><table id="auditTable"></table></div>',
'  </section>',

/* ---- dashboard ---- */
'  <section class="panel" id="panel-dash" hidden>',
'    <div class="tiles" id="dashTiles"></div>',
'    <div class="card card-pad">',
'      <div class="row"><h2 class="sec">Attention required</h2><div class="spacer"></div>',
'        <span class="faint" id="attnCount"></span></div>',
'      <p class="sec">Out of stock, critical and low items for the location above.</p>',
'    </div>',
'    <div class="wrap"><table id="attnTable"></table></div>',
'    <div class="card card-pad" id="cardLocValue">',
'      <div class="row"><h2 class="sec">Value by location</h2></div>',
'      <div class="wrap" style="margin-top:9px;border:0"><table id="locTable"></table></div>',
'    </div>',
'    <div class="card card-pad" id="cardRecentTakes">',
'      <h2 class="sec">Recent stock takes</h2>',
'      <div class="wrap" style="margin-top:9px;border:0"><table id="recentTakes"></table></div>',
'    </div>',
'  </section>',
'</main>',
'<dialog id="sheet"></dialog>',
'<dialog id="light" class="lightbox"></dialog>',
'<input type="file" id="photoFile" accept="image/*" hidden>',
'<input type="file" id="csvFile" accept=".csv,text/csv" hidden>'
].join('');
